language: python
python:
  - "3.7"
  - "3.3"
  - "2.7"
  - "2.6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install .
  - pip install nose coverage
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:  
  - python setup.py nosetests --with-coverage --cover-package pypiview
  - coverage
  - coveralls
 
after_sucess:
  coveralls
<<<<<<< HEAD
  codecov
=======
  codecov
  
  
>>>>>>> a6d76adb4566707dd7bcefc769187e4f0d468d63
