language: python

python:
    - 3.6.3

install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install coveralls

script:
    - py.test --cov=endpoints

after_success:
    - coveralls
