language: python

python:
    - 3.6.3

install:
    - pip install -r requirements.txt
    - pip install pytest-cov

script:
    - py.test --cov

after_success:
    - coveralls
    - codeclimate-test-reporter
