language: python

python:
    - 3.6.3

install:
    - pip install -r requirements.txt
    - pip install pytest-cov

script:
    - py.test --cov=https://coveralls.io/github/bearded7/StoreManager-Flask-and-Python-API

after_success:
    - coveralls
